[build]
    command="npm run build"
    publish="/build"
    base="/"

[[redirects]]
    from="/*"
    to="index.html"
    status=200

[build.environment]
    URL="https://incumons.herokuapp.com"
    AUTH="https://incumons.herokuapp.com/check-logged-in-user"
    LOGOUT="https://incumons.herokuapp.com/logout"
    CHANGE_PASSWORD="https://incumons.herokuapp.com/change/password"
    CANCEL_SELL="https://incumons.herokuapp.com/cancel/sell/nft"
    BUY_NFT="https://incumons.herokuapp.com/buy/nft"
    SELL_NFT="https://incumons.herokuapp.com/sell/nft"
    GET_TRANSACS="https://incumons.herokuapp.com/user/transactions/get-all"
    MINT_BOX="https://incumons.herokuapp.com/mint/box"
    GET_ALL_NFT="https://incumons.herokuapp.com/user/nft/get-all"
    GET_MP_NFT="https://incumons.herokuapp.com/nft/get-all"
    VERIF_EMAIL="https://incumons.herokuapp.com/verify/email"
    REG_USER="https://incumons.herokuapp.com/register"
    LOGIN_USER="https://incumons.herokuapp.com/login"
    GET_TOKEN="https://incumons.herokuapp.com/getToken"
    FORGET_PW="https://incumons.herokuapp.com/forgot-password"
    RESET_PW="https://incumons.herokuapp.com/reset/password"
    NODE_ENV="development"

[[headers]]
    for = "/*"
    [headers.values]
    Strict-Transport-Security = '''
            max-age=31536000;
            includeSubDomains
    '''
    X-Content-Type-Options = "nosniff"
    X-Frame-Options =  "deny"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    cache-control = '''
        must-revalidate
    '''
    Content-Security-Policy = '''
        default-src 'self';
        style-src *;
        img-src *;
        font-src *;
        connect-src i.ibb.co *.i.ibb.co incumons.herokuapp.com *.incumons.herokuapp.com incumon.netlify.app *.incumon.netlify.app fonts.googleapis.com *.fonts.googleapis.com fonts.gstatic.com *.onts.gstatic.com;
    '''
    Feature-Policy = "accelerometer 'none'; autoplay 'none'; camera 'none'; encrypted-media 'none'; fullscreen 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'none'; picture-in-picture 'none'; usb 'none'"
    Permissions-Policy = '''
        accelerometer=(),
        autoplay=(),
        camera=(),
        encrypted-media=(),
        fullscreen=(),
        geolocation=(),
        gyroscope=(),
        magnetometer=(),
        microphone=(),
        midi=(),
        payment=(),
        picture-in-picture=(),
        usb=(),
    '''