[build]
    command="npm run build"
    publish="/build"
    base="/"

[[redirects]]
    from="/*"
    to="index.html"
    status=200

[build.environment]
    URL="http://localhost:5000"
    AUTH="http://localhost:5000/check-logged-in-user"
    LOGOUT="http://localhost:5000/logout"
    CHANGE_PASSWORD="http://localhost:5000/change/password"
    CANCEL_SELL="http://localhost:5000/cancel/sell/nft"
    BUY_NFT="http://localhost:5000/buy/nft"
    SELL_NFT="http://localhost:5000/sell/nft"
    GET_TRANSACS="http://localhost:5000/user/transactions/get-all"
    MINT_BOX="http://localhost:5000/mint/box"
    GET_ALL_NFT="http://localhost:5000/user/nft/get-all"
    GET_MP_NFT="http://localhost:5000/nft/get-all"
    VERIF_EMAIL="http://localhost:5000/verify/email"
    REG_USER="http://localhost:5000/register"
    LOGIN_USER="http://localhost:5000/login"
    GET_TOKEN="http://localhost:5000/getToken"
    FORGET_PW="http://localhost:5000/forgot-password"
    RESET_PW="http://localhost:5000/reset/password"
