[build]
    command="npm run build"
    publish="/build"
    base="/"

[[redirects]]
    from="/*"
    to="index.html"
    status=200

[build.environment]
    URL="https://incumons.heroku.app"
    AUTH="https://incumons.heroku.app/check-logged-in-user"
    LOGOUT="https://incumons.heroku.app/logout"
    CHANGE_PASSWORD="https://incumons.heroku.app/change/password"
    CANCEL_SELL="https://incumons.heroku.app/cancel/sell/nft"
    BUY_NFT="https://incumons.heroku.app/buy/nft"
    SELL_NFT="https://incumons.heroku.app/sell/nft"
    GET_TRANSACS="https://incumons.heroku.app/user/transactions/get-all"
    MINT_BOX="https://incumons.heroku.app/mint/box"
    GET_ALL_NFT="https://incumons.heroku.app/user/nft/get-all"
    GET_MP_NFT="https://incumons.heroku.app/nft/get-all"
    VERIF_EMAIL="https://incumons.heroku.app/verify/email"
    REG_USER="https://incumons.heroku.app/register"
    LOGIN_USER="https://incumons.heroku.app/login"
    GET_TOKEN="https://incumons.heroku.app/getToken"
    FORGET_PW="https://incumons.heroku.app/forgot-password"
    RESET_PW="https://incumons.heroku.app/reset/password"
