[build]
    command="npm run build"
    publish="/build"
    base="/"

[[redirects]]
    from="/*"
    to="index.html"
    status=200

[build.environment]
    URL="https://incumons.onrender.com"
    AUTH="https://incumons.onrender.com/check-logged-in-user"
    LOGOUT="https://incumons.onrender.com/logout"
    CHANGE_PASSWORD="https://incumons.onrender.com/change/password"
    CANCEL_SELL="https://incumons.onrender.com/cancel/sell/nft"
    BUY_NFT="https://incumons.onrender.com/buy/nft"
    SELL_NFT="https://incumons.onrender.com/sell/nft"
    GET_TRANSACS="https://incumons.onrender.com/user/transactions/get-all"
    MINT_BOX="https://incumons.onrender.com/mint/box"
    GET_ALL_NFT="https://incumons.onrender.com/user/nft/get-all"
    GET_MP_NFT="https://incumons.onrender.com/nft/get-all"
    VERIF_EMAIL="https://incumons.onrender.com/verify/email"
    REG_USER="https://incumons.onrender.com/register"
    LOGIN_USER="https://incumons.onrender.com/login"
    GET_TOKEN="https://incumons.onrender.com/getToken"
    FORGET_PW="https://incumons.onrender.com/forgot-password"
    RESET_PW="https://incumons.onrender.com/reset/password"
    NODE_ENV="development"

[[headers]]
    for = "/*"
    [headers.values]
    Strict-Transport-Security = '''
            max-age=31536000;
            includeSubDomains
    '''
    X-Content-Type-Options = "nosniff"
    X-Frame-Options =  "deny"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    cache-control = '''
        must-revalidate
    '''
    Content-Security-Policy = '''
        default-src 'self' 'strict-dynamic' https:;
        frame-ancestors 'none';
        frame-src 'none';
        object-src 'none';
        base-uri 'none';
        script-src 'self';
        style-src 'self' fonts.googleapis.com *.fonts.googleapis.com fonts.gstatic.com *.fonts.gstatic.com 'unsafe-inline';
        img-src 'self';
        font-src 'self' fonts.googleapis.com *.fonts.googleapis.com fonts.gstatic.com *.fonts.gstatic.com;
        connect-src 'self' incumons.onrender.com *.incumons.onrender.com fonts.googleapis.com *.fonts.googleapis.com fonts.gstatic.com *.fonts.gstatic.com;
    '''
    Permissions-Policy = '''
        accelerometer=(), 
        autoplay=(), 
        camera=(), 
        cross-origin-isolated=(), 
        display-capture=(), 
        document-domain=(), 
        encrypted-media=(), 
        fullscreen=(), 
        geolocation=(), 
        gyroscope=(), 
        keyboard-map=(),
        magnetometer=(),  
        microphone=(), 
        midi=(), 
        payment=(), 
        picture-in-picture=(),
        publickey-credentials-get=(), 
        screen-wake-lock=(), 
        sync-xhr=(), 
        usb=(), 
        web-share=(), 
        xr-spatial-tracking=()
    '''
