export const config = {
   URL: process.env.URL,
   AUTH: process.env.AUTH,
   LOGOUT: process.env.LOGOUT,
   CHANGE_PASSWORD: process.env.CHANGE_PASSWORD,
   CANCEL_SELL: process.env.CANCEL_SELL,
   BUY_NFT: process.env.BUY_NFT,
   SELL_NFT: process.env.SELL_NFT,
   GET_TRANSACS: process.env.GET_TRANSACS,
   MINT_BOX: process.env.MINT_BOX,
   GET_ALL_NFT: process.env.GET_ALL_NFT,
   GET_MP_NFT: process.env.GET_MP_NFT,
   VERIF_EMAIL: process.env.VERIF_EMAIL,
   REG_USER: process.env.REG_USER,
   LOGIN_USER: process.env.LOGIN_USER,
   GET_TOKEN: process.env.GET_TOKEN,
   FORGET_PW: process.env.FORGET_PW,
   RESET_PW: process.env.RESET_PW,
}
